/* eslint global-require: 0 */

export default {
  AboutScreen: require('./AboutScreen').default,
  AddressScreen: require('./Registration/2.5-AddressScreen').default,
  AgendaScreen: require('./Legislation/AgendaScreen').default,
  AllElectedRepsScreen: require('./ElectedRep/AllElectedRepsScreen').default,
  AuditVoteScreen: require('./Legislation/AuditVoteScreen').default,
  BillScreen: require('./Legislation/BillScreen').default,
  CameraScreen: require('./Registration/3.3-CameraScreen').default,
  ConfirmDelegateScreen: require('./Delegation/ConfirmDelegateScreen').default,
  ConfirmVoteScreen: require('./Legislation/ConfirmVoteScreen').default,
  DelegateInfoScreen: require('./Delegation/DelegateInfoScreen').default,
  DelegatesScreen: require('./Delegation/DelegatesScreen').default,
  DistrictsMapScreen: require('./ElectedRep/DistrictsMapScreen').default,
  ElectedRepScreen: require('./ElectedRep/ElectedRepScreen').default,
  EmailScreen: require('./Registration/4-EmailScreen').default,
  EnterSMSCodeScreen: require('./Login/2-EnterSMSCodeScreen').default,
  FeedbackScreen: require('./FeedbackScreen/FeedbackScreen').default,
  FirstNameScreen: require('./Registration/1-FirstNameScreen').default,
  HomeScreen: require('./HomeScreen/HomeScreen').default,
  IdReviewScreen: require('./Registration/3.6-IdReviewScreen').default,
  InvalidSessionScreen: require('./InvalidSessionScreen').default,
  LastNameScreen: require('./Registration/1.5-LastNameScreen').default,
  LegalIdScreen: require('./Registration/3-LegalIdScreen').default,
  LiquidDotVoteScreen: require('./Login/LiquidDotVoteScreen').default,
  LoadBillScreen: require('./Legislation/LoadBillScreen').default,
  LoginScreen: require('./Login/LoginScreen').default,
  RegistrationIntroScreen: require('./Registration/0-RegistrationIntroScreen').default,
  RequestsScreen: require('./Delegation/RequestsScreen').default,
  ThankYouScreen: require('./Registration/5-ThankYouScreen').default,
  TrumpApprovalScreen: require('./TrumpApprovalScreen/TrumpApprovalScreen').default,
  VotingPowerScreen: require('./VotingPowerScreen/VotingPowerScreen').default,
  YourRegistrationScreen: require('./Registration/YourRegistrationScreen').default,
  ZipScreen: require('./Registration/2-ZipScreen').default,
}
